# Generated by Django 6.0.2 on 2026-03-18 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_opening_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura de caja',
                'verbose_name_plural': 'Aperturas de caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GYM', 'GYM'), ('NEVERA', 'NEVERA'), ('CAFÉ', 'CAFÉ'), ('HERBALIFE', 'HERBALIFE'), ('PROTEINA', 'PROTEINA')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('VENTAS', 'VENTAS'), ('PAGOS', 'PAGOS'), ('MANUAL', 'MANUAL')], max_length=10)),
                ('cash_opening', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_cash_opening', to='sales.cashopening')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashopening',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('is_open', 'created_at'), name='only_one_open_cash_opening'),
        ),
    ]
