# Generated by Django 6.0.2 on 2026-03-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='cash_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_cash_opening', to='sales.cashopening'),
        ),
    ]
