# Generated by Django 6.0.2 on 2026-03-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_income_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashopening',
            name='only_one_open_cash_opening',
        ),
        migrations.AlterField(
            model_name='cashopening',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
