# Generated by Django 6.0.2 on 2026-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_income_cash_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('GYM', 'GYM'), ('NEVERA', 'NEVERA'), ('CAFÉ', 'CAFÉ'), ('HERBALIFE', 'HERBALIFE'), ('PROTEINA', 'PROTEINA'), ('SOBRANTE', 'SOBRANTE')], max_length=20),
        ),
    ]
