# Generated by Django 6.0.2 on 2026-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
