# Generated by Django 6.0.2 on 2026-03-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_income_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateField(editable=False),
        ),
    ]
