# Generated by Django 6.0.2 on 2026-03-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=10, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador'), ('Secretario(a)', 'Secretario(a)')], default='Cliente', max_length=13)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/images')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PP', 'Pasaporte'), ('RC', 'Registro Civil'), ('PPT', 'Permiso por Protección Temporal')], default='CC', max_length=100)),
                ('document_number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.member',),
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('biceps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mid_abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lower_abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adductor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_measurement', to='accounts.client')),
            ],
        ),
    ]
