# Generated by Django 6.0.2 on 2026-03-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment',
        ),
    ]
