# Generated by Django 6.0.2 on 2026-03-24 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='frozen_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
