# Generated by Django 6.0.2 on 2026-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='notified_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
