# Generated by Django 6.0.2 on 2026-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Gimnasio', max_length=100)),
                ('app_description', models.CharField(default='Panel de administración', max_length=200)),
                ('app_image', models.ImageField(blank=True, null=True, upload_to='management/images/')),
                ('app_logo', models.ImageField(blank=True, null=True, upload_to='management/images/')),
                ('elements_per_section', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
